### ISSUE TITLE
Detect changes with pull requests

### ISSUE THREAD

**Issue by EndBug** [EndBug/version-check#15]
Hey @hmehta, I'll ask you because PR #14 is yours.
I've fixed the code so that it triggers correctly when a PR is updated. The question is: does it need to check whether the version has changed in the whole PR  (which makes more sense to me) or just in the latest commit (which to me seems less useful and probably harder to implement if the commits are more than 20)?
I'd just like to have a second opinion :)

**Comment by hmehta** [comment]
I think it should always check all the commits in the PR - consider the following case:

1. Developer does some amount of work
2. Developer bumps the version and pushes, version check says everything is a-ok
3. Now the reviewer starts reviewing the code and finds stuff that he would like to change
4. The original developer does the suggested changes and pushes

Now there is a valid version bump done in the PR compared to the branch the original developer intended to target, but if the tooling only checks the latest commit it will result into failure in this case.

I would leave enforcing rules like "version bump must be the latest commit on all branches/PRs" up to teams instead of enforcing that in tooling.

Just my 50c though :)

**Comment by EndBug** [comment]
Done!
The action has been updated to `v1.3.0` and now supports PR, as long as a new `commit` output.
Thanks for your help!
