### ISSUE TITLE
[Feature] Ability to exit if not changed

### ISSUE THREAD

**Issue by prescottprue** [EndBug/version-check#16]
Love the action, thanks for making it!

It seems like it would be common to want to skip all of the rest of the workflow if the version has not changed. Not sure this is necessarily possible in the current setup, but it would be really sweet if I didn't have to put the if statements on all of the steps following this one. If instead there was just an option to successfully exit with a 0 exit code if the version hadn't changed, then the if statements on all following steps wouldn't be required

**Describe the solution you'd like**
An option which can be passed to `version-check` which would have the action exit if the version hasn't changed - maybe `exitIfNotChanged: true`?

**Comment by EndBug** [comment]
Hi, thanks for writing!
Unfortunately, I think there's no way this can be done: actions don't have the power to "break" from the workflow, they can only either fail or succeed.

If you don't want to add the `if` statements everywhere you could use two separate jobs: the first with a final step that checks if the version hasn't changed and if so throws an error (using a shell command), the second that runs only if the first one is successful (with the `needs` parameter).
I know that this is not ideal since you would have a failing job every time the version is not changed, but I'm afraid that the only alternative.

Let me know if you need anything else :)

**Comment by prescottprue** [comment]
Thought so, thanks for clarifying. We can close this issue since it won't able to be supported
