### ISSUE TITLE
Does not consider a change then revert

### ISSUE THREAD

**Issue by wasabigeek** [EndBug/version-check#18]
Really more an edge case - since the action looks at each individual commit, if a version is changed but then reverted in a later commit, it will still interpret it as a version change.

I think the benefit of fixing it might not be high, but maybe we could update the documentation to mention this? Will be happy to submit a PR if that's OK.

**Comment by EndBug** [comment]
I'm not sure I totally get what you're saying: is it that when a commit gets reverted it is detected as a version change, while you want it not to be detected?

**Comment by EndBug** [comment]
Could you give me an example with the current behavior and the intended one?
(Sorry, this is not my native language 😅)

**Comment by wasabigeek** [comment]
No worries! Maybe I misunderstand too. Steps to reproduce:
- create a commit with a version bump in the diff (e.g. update package.json manually)
- `git revert` the commit

Expected:
- should return `false` since overall there is no bump

Actual
- returns `true` because it exits early once a matching commit is found

I think this is reasonable behaviour though (realistically, I don't think anyone would do that, I was doing it only to test the action), just worth documenting in the README.

**Comment by EndBug** [comment]
Oh ok I get it
I get your concern, but it seems like it would be way too much work to check for reverts too, since the action is meant to search for one change for every push event.

I've figured a way to make it work:
- use `file-url` by setting it to the commit before the push event; you can type `::before` and the action will fill the URL for you
- use `static-checking` to check the current version against the one before the workflow event; set it to `localIsNew`, since you expect the pushed version to be equal (if not changed or reverted) or newer than the previous one.

That should do the trick! It would be awesome if you could test the change I've just pushed to see whether there is something to fix: just use `EndBug/version-check@master` for now

**Comment by EndBug** [comment]
@wasabigeek ...

**Comment by wasabigeek** [comment]
Hey @EndBug apologies, when I get time I'll give it a try? This issue was more to raise an edge case (hence why I suggested a documentation change would be enough) than an actual blocker to our workflow :)

**Comment by EndBug** [comment]
@all-contributors please add @wasabigeek for ideas

**Comment by EndBug** [comment]
Hey, I've decided to publish it anyway, since my tests seem ok. You can find this feature in `v1.5.0` (also in `v1` and `latest`)
Thanks for the issue ;)
