### ISSUE TITLE
[Bug] static-checking: localIsNew works incorrectly

### ISSUE THREAD

**Issue by ruscon** [EndBug/version-check#40]
**Describe the bug**
if use `static-checking: localIsNew` and the latest published npm package version greater than the local package version then `outputs.changed` will be eq `true`

*example:*
latest published pm package version: 4.0.1
local package version: 4.0.0

**To Reproduce**
My action configuration: https://github.com/goparrot/geocoder/commit/fdef1e85f8927188635873330694572ed84ff3c2#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R31-R36

result: https://github.com/goparrot/geocoder/runs/2104611216?check_suite_focus=true

debug
```
Run EndBug/version-check@v1
  with:
    file-url: https://unpkg.com/@goparrot/geocoder@latest/package.json
    static-checking: localIsNew
Searching for version update...
Static-checking files...
  Package file name: "package.json"
  Package file URL: "https://unpkg.com/@goparrot/geocoder@latest/package.json"
Found match for version 4.0.0
```

**Expected behavior**
`outputs.changed` should be `false`

**Comment by EndBug** [comment]
Hi, thanks for opening the issue
This behavior is actually kind of intended: when you use `localIsNew` you're asserting that the local version will be newer. The action shows that there has been a change because there actually are two different versions.
The way I think you should be able to solve this is by checking the `type` output: since there are no "reverse" type of updates, that should be either `undefined` or `null`.

From the docs of the `static-checking` type:
>  Please note that using the wrong value may make the action detect the change but fail to identify the type.

Try logging the outputs of the action and see what their value ends up being, then you can check using them too.

I know this is not a really practical solution, but it should work for now. I should add a way to ditch `localIsNew` and `remoteIsNew` altogether in the future

**Comment by ruscon** [comment]
@EndBug Ok, thx.
