### ISSUE TITLE
Output is always empty

### ISSUE THREAD

**Issue by sergeyzwezdin** [EndBug/version-check#7]
**Describe the bug**

When I try to use the action, it always skips next steps because of output is empty.

**To Reproduce**

Check out [my workflow](https://github.com/pixel-grid/pixelgrid/blob/master/.github/workflows/publish.yml). It always [skips](https://github.com/pixel-grid/pixelgrid/commit/4759cda7d75f11238366311baba35379cd980de4/checks?check_suite_id=270414249) further steps even if I change the version.

**Expected behavior**

It should run the next steps if version changed.

**Screenshots**

![image](https://user-images.githubusercontent.com/800755/67067112-90e3a980-f18e-11e9-8509-85bf72c05066.png)

**Comment by EndBug** [comment]
This is weird, it seems like the action isn't picking up your arguments entirely: you can see that by looking at the logs 
Just for troubleshooting: try using the v1.1.0 version and checking out the repo with the "master" ref

**Comment by EndBug** [comment]
@sergeyzwezdin Your publish file wasn't including the `diff-search` option the last time you changed the version. You added that argument, which should make your workflow work properly, with commit [`4759cda`](https://github.com/pixel-grid/pixelgrid/commit/4759cda7d75f11238366311baba35379cd980de4), which was made after the last version change (in commit [`13aa164`](https://github.com/pixel-grid/pixelgrid/commit/13aa1646d144b0f7c0bfee3b3c227d83afd2bce5)).
That argument is crucial because you are not updating the version though normal `npm version` commits, but only via manual changes: that makes it impossible for the action to detect the changes if you don't explicitly check the `diff-search` option, which looks in the diff of every commit.

Your workflow should run fine on your next version change.

**Comment by sergeyzwezdin** [comment]
Thank you @EndBug for explanation 👍🏻 Very appreciated.

And another question. Recently I created private repo and the action didn't work returning the following error:

> Error: Request failed with status code 404

Once I converted the repo into public it started working.

https://github.com/sergeyzwezdin/actions-test/commit/62ce369b5b1334cc8fa23d0a342e833da9aff333/checks?check_suite_id=275117829

https://github.com/sergeyzwezdin/actions-test/commit/06a578b309174816da3839ab63eb19603ced8620/checks?check_suite_id=275130285

Is it supposed not to work in private repos?

**Comment by EndBug** [comment]
That's actually a valid question, I will soon create a new issue to address that. In the meantime, I'll close this one ;)
